apiVersion: apps/v1
kind: Deployment

metadata:
  name: mongo
  namespace: devops-ecommerce

spec:
  replicas: 1

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: mongo

  template:
    metadata:
      labels:
        app: mongo

    spec:
      containers:
        - name: mongo
          image: mongo:7
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 27017

          volumeMounts:
            - name: mongo-data
              mountPath: /data/db

          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 6

          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 6

          resources:
            requests:
              memory: "192Mi"
              cpu: "25m"
            limits:
              memory: "384Mi"
              cpu: "300m"

      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc