apiVersion: policy/v1
kind: PodDisruptionBudget

metadata:
  name: api-gateway-pdb
  namespace: devops-ecommerce

spec:
  minAvailable: 1

  selector:
    matchLabels:
      app: api-gateway


---

apiVersion: policy/v1
kind: PodDisruptionBudget

metadata:
  name: frontend-gateway-pdb
  namespace: devops-ecommerce

spec:
  minAvailable: 1

  selector:
    matchLabels:
      app: frontend-gateway


---

apiVersion: policy/v1
kind: PodDisruptionBudget

metadata:
  name: product-service-pdb
  namespace: devops-ecommerce

spec:
  minAvailable: 1

  selector:
    matchLabels:
      app: product-service


---

apiVersion: policy/v1
kind: PodDisruptionBudget

metadata:
  name: order-service-pdb
  namespace: devops-ecommerce

spec:
  minAvailable: 1

  selector:
    matchLabels:
      app: order-service


---

apiVersion: policy/v1
kind: PodDisruptionBudget

metadata:
  name: user-service-pdb
  namespace: devops-ecommerce

spec:
  minAvailable: 1

  selector:
    matchLabels:
      app: user-service