apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: devops-ecommerce
type: Opaque
stringData:
  POSTGRES_USER: "orderuser"
  POSTGRES_PASSWORD: "orderpass"
  POSTGRES_DB: "orderdb"
  DATABASE_URL: "postgresql://orderuser:orderpass@postgres:5432/orderdb"