apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: grafana

  template:
    metadata:
      labels:
        app: grafana

    spec:
      securityContext:
        fsGroup: 472

      containers:
        - name: grafana
          image: grafana/grafana:13.2.0

          ports:
            - containerPort: 3000

          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-admin
                  key: admin-user

            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-admin
                  key: admin-password

            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"

          resources:
            requests:
              cpu: 50m
              memory: 150Mi

            limits:
              cpu: 400m
              memory: 450Mi
            
          startupProbe:
            httpGet:
              path: /api/health
              port: 3000
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 18

          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 5

          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana

            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources/datasource.yaml
              subPath: datasource.yaml

            - name: dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards/provider.yaml
              subPath: provider.yaml

            - name: dashboard
              mountPath: /etc/grafana/dashboards/devops-overview.json
              subPath: devops-overview.json

      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-data

        - name: datasources
          configMap:
            name: grafana-datasources

        - name: dashboard-provider
          configMap:
            name: grafana-dashboard-provider

        - name: dashboard
          configMap:
            name: grafana-dashboard