apiVersion: v1
kind: Service
metadata:
  name: frontend-gateway
  namespace: devops-ecommerce
spec:
  type: ClusterIP

  selector:
    app: frontend-gateway

  ports:
    - name: http
      port: 8080
      targetPort: 8080