apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: devops-ecommerce
spec:
  type: NodePort

  selector:
    app: api-gateway

  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080