apiVersion: apps/v1
kind: Deployment

metadata:
  name: order-service
  namespace: devops-ecommerce

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  minReadySeconds: 10

  selector:
    matchLabels:
      app: order-service

  template:
    metadata:
      labels:
        app: order-service

    spec:
      nodeSelector:
        workload: order

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: order-service
              topologyKey: kubernetes.io/hostname

      containers:
        - name: order-service
          image: docker.io/arhammrashid17/devops-ecommerce-order:19-6d7a91d
          imagePullPolicy: Always

          ports:
            - containerPort: 4002

          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ORDER_PORT

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL

            - name: API_GATEWAY_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: API_GATEWAY_URL

          readinessProbe:
            httpGet:
              path: /health
              port: 4002
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /health
              port: 4002
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"

            limits:
              memory: "256Mi"
              cpu: "500m"