apiVersion: apps/v1
kind: Deployment

metadata:
  name: product-service
  namespace: devops-ecommerce

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  minReadySeconds: 10

  selector:
    matchLabels:
      app: product-service

  template:
    metadata:
      labels:
        app: product-service

    spec:
      nodeSelector:
        workload: product

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: product-service
              topologyKey: kubernetes.io/hostname

      containers:
        - name: product-service
          image: docker.io/arhammrashid17/devops-ecommerce-product:17-43daac3
          imagePullPolicy: Always

          ports:
            - containerPort: 4001

          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PRODUCT_PORT

            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_URI

          readinessProbe:
            httpGet:
              path: /health
              port: 4001
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /health
              port: 4001
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"

            limits:
              memory: "256Mi"
              cpu: "500m"