apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: devops-ecommerce
spec:
  type: ClusterIP

  selector:
    app: user-service

  ports:
    - name: http
      port: 4003
      targetPort: 4003